# Generated by Django 5.2.6 on 2025-09-17 07:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingTraveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20)),
                ('age_group', models.CharField(choices=[('0-5', '0-5 years'), ('6-12', '6-12 years'), ('13-17', '13-17 years'), ('18-24', '18-24 years'), ('25-34', '25-34 years'), ('35-44', '35-44 years'), ('45-54', '45-54 years'), ('55-64', '55-64 years'), ('65+', '65+ years')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('is_primary_traveler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('timestamp', models.DateTimeField()),
                ('transport_mode', models.CharField(blank=True, choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('public_transport', 'Public Transport'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('unknown', 'Unknown')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(max_length=20, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('purpose', models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('shopping', 'Shopping'), ('recreation', 'Recreation'), ('medical', 'Medical'), ('social', 'Social'), ('other', 'Other')], max_length=20)),
                ('transport_mode', models.CharField(choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('public_transport', 'Public Transport'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('unknown', 'Unknown')], max_length=20)),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('co2_emission', models.FloatField(default=0.0, help_text='CO2 emission in kg')),
                ('co2_saved', models.FloatField(default=0.0, help_text='CO2 saved in kg')),
                ('consent_given', models.BooleanField(default=False)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('trip_chain', models.JSONField(default=list, help_text='Related trip IDs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('device_os', models.CharField(blank=True, max_length=50)),
                ('device_version', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery level percentage', null=True)),
                ('accelerometer_x', models.FloatField(blank=True, null=True)),
                ('accelerometer_y', models.FloatField(blank=True, null=True)),
                ('accelerometer_z', models.FloatField(blank=True, null=True)),
                ('gyroscope_x', models.FloatField(blank=True, null=True)),
                ('gyroscope_y', models.FloatField(blank=True, null=True)),
                ('gyroscope_z', models.FloatField(blank=True, null=True)),
                ('magnetometer_x', models.FloatField(blank=True, null=True)),
                ('magnetometer_y', models.FloatField(blank=True, null=True)),
                ('magnetometer_z', models.FloatField(blank=True, null=True)),
                ('traffic_level', models.FloatField(blank=True, help_text='Traffic level 0-100', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
