# Generated by Django 5.2.6 on 2025-09-17 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0, help_text='Total distance in meters')),
                ('total_duration', models.BigIntegerField(default=0, help_text='Total duration in seconds')),
                ('total_co2_emission', models.FloatField(default=0.0, help_text='Total CO2 emission in kg')),
                ('total_co2_saved', models.FloatField(default=0.0, help_text='Total CO2 saved in kg')),
                ('average_eco_score', models.FloatField(default=0.0, help_text='Average eco score')),
                ('walking_trips', models.PositiveIntegerField(default=0)),
                ('cycling_trips', models.PositiveIntegerField(default=0)),
                ('public_transport_trips', models.PositiveIntegerField(default=0)),
                ('private_vehicle_trips', models.PositiveIntegerField(default=0)),
                ('work_trips', models.PositiveIntegerField(default=0)),
                ('education_trips', models.PositiveIntegerField(default=0)),
                ('shopping_trips', models.PositiveIntegerField(default=0)),
                ('recreation_trips', models.PositiveIntegerField(default=0)),
                ('medical_trips', models.PositiveIntegerField(default=0)),
                ('social_trips', models.PositiveIntegerField(default=0)),
                ('other_trips', models.PositiveIntegerField(default=0)),
                ('excellent_data_count', models.PositiveIntegerField(default=0)),
                ('good_data_count', models.PositiveIntegerField(default=0)),
                ('fair_data_count', models.PositiveIntegerField(default=0)),
                ('poor_data_count', models.PositiveIntegerField(default=0)),
                ('households_surveyed', models.PositiveIntegerField(default=0)),
                ('households_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origin_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('frequency', models.PositiveIntegerField(help_text='Number of times this route was taken')),
                ('average_duration', models.FloatField(help_text='Average duration in seconds')),
                ('transport_modes', models.JSONField(default=list, help_text='Most common transport modes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('origin_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origin_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('max_time', models.IntegerField(help_text='Maximum time in seconds')),
                ('min_safety_score', models.FloatField(help_text='Minimum safety score 0-100')),
                ('max_distance', models.FloatField(help_text='Maximum distance in meters')),
                ('preferred_modes', models.JSONField(default=list, help_text='Preferred transport modes')),
                ('avoid_congestion', models.BooleanField(default=True)),
                ('eco_friendly', models.BooleanField(default=True)),
                ('max_co2_emission', models.FloatField(help_text='Maximum CO2 emission in kg')),
                ('optimal_route', models.JSONField(help_text='Optimal route data')),
                ('alternative_routes', models.JSONField(default=list, help_text='Alternative routes')),
                ('total_time', models.IntegerField(help_text='Total time in seconds')),
                ('total_distance', models.FloatField(help_text='Total distance in meters')),
                ('total_co2_emission', models.FloatField(help_text='Total CO2 emission in kg')),
                ('average_safety_score', models.FloatField(help_text='Average safety score')),
                ('average_congestion_level', models.FloatField(help_text='Average congestion level')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficAlert',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('alert_type', models.CharField(choices=[('congestion', 'Congestion'), ('accident', 'Accident'), ('construction', 'Construction'), ('weather', 'Weather'), ('event', 'Event')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('estimated_delay', models.IntegerField(help_text='Estimated delay in minutes')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
